apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cloudchamp
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: cloudacademydevops/api:v3
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONN_STR
              value: "mongodb://mongo-0.cloudchamp.svc.cluster.local:27017/langdb?replicaSet=rs0"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always

